# https://docs.travis-ci.com/user/languages/php
language: php
sudo: required

# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=REL1_29; PHPUNIT=5.7.*
      php: 7.1
    - env: DB=mysql; MW=master; PHPUNIT=6.5.*
      php: 7.3
    - env: DB=mysql; MW=REL1_28; FUSEKI=2.4.0; PHPUNIT=4.8.*
      php: 5.6
    - env: DB=mysql; MW=REL1_27; VIRTUOSO=6.1; PHPUNIT=4.8.*
      php: 5.6
    - env: DB=mysql; MW=REL1_27; SESAME=2.8.7; PHPUNIT=4.8.*
      php: 5.6
    - env: DB=sqlite; MW=REL1_27; SITELANG=ja; PHPUNIT=4.8.*
      php: 5.6
    - env: DB=postgres; MW=REL1_31; PHPUNIT=6.5.*
      php: 7.2
    - env: DB=mysql; MW=REL1_27; BLAZEGRAPH=1.5.2; PHPUNIT=4.8.*
      php: 5.6
    - env: DB=mysql; MW=REL1_30; ES=5.6.6; PHPUNIT=5.7.*
      php: 7.1
    - env: DB=mysql; MW=REL1_31; TYPE=benchmark; PHPUNIT=6.5.*
      php: 7.2
    - env: DB=sqlite; MW=REL1_32; PHPUNIT=6.5.*
      php: 7.3
    - env: DB=sqlite; MW=REL1_27; TYPE=composer; PHPUNIT=4.8.*
      php: 5.6
    - env: DB=mysql; MW=REL1_27; TYPE=relbuild; PHPUNIT=4.8.*
      php: 5.6
  allow_failures:
    # Can fail when pushed/used with newly Composer dependencies
    - env: DB=mysql; MW=REL1_27; TYPE=relbuild; PHPUNIT=4.8.*
    # Can fail when pushed/used with newly Composer dependencies
    - env: DB=sqlite; MW=REL1_27; TYPE=composer; PHPUNIT=4.8.*
    # This is MW master, you never know what WMF developers have put in for easter eggs, same for PHP conversely
    - env: DB=mysql; MW=master; PHPUNIT=6.5.*
    # May take a moment and is non-critical therefore allow it to run without delaying the status
    - env: DB=mysql; MW=REL1_31; TYPE=benchmark; PHPUNIT=6.5.*
    - env: DB=mysql; MW=REL1_27; SESAME=2.8.7
    - env: DB=mysql; MW=REL1_30; ES=5.6.6; PHPUNIT=5.7.*


# Dec 16, 2015 (GCE switch): Travis support wrote (Tomcat + Java):
# bug in the JDK: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7089443.
# The hostname for the precise-gce platform is longer than 64 characters on the
# VM your job is running on
#- sudo hostname "$(hostname | cut -c1-63)"
#- sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
#- cat /etc/hosts # optionally check the content *after*

# Aug 12, 2016: (incident:2p40l49r3yxd) Travis support asks to add `sudo sysctl ...`
# After investigation, removed the lines from Dec 16, 2015 as it emptied the hosts file
before_install:
  - phpenv config-rm xdebug.ini # https://github.com/travis-ci/travis-ci/issues/1697
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - ip addr # for confirmation. can be skipped
  - cat /etc/hosts # optionally check the content *before*

install:
  - travis_retry composer self-update
  - bash ./tests/travis/install-services.sh
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-mediawiki.sh

before_script:
  - bash ./tests/travis/update-configuration-settings.sh

script:
  - bash ./tests/travis/run-tests.sh

after_script:
  - if [ ls /tmp/stacktrace* 1> /dev/null 2>&1 ] ; then cat /tmp/stacktrace*.log ; fi
  - if [ -f php.log ] ; then cat php.log ; fi
  - if [ -f /tmp/mediawiki-debug.log ] ; then cat /tmp/mediawiki-debug.log ; fi

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

cache:
  directories:
    - $HOME/.composer/cache
