language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=master@5cc1f1d; TYPE=coverage
      php: 5.3
    - env: DB=sqlite; MW=master@5cc1f1d; TYPE=composer
      php: 5.6
    - env: DB=mysql; MW=1.19.20; TYPE=relbuild
      php: 5.4
    - env: DB=mysql; MW=1.23.5; FUSEKI=1.1.1
      php: 5.4
    - env: DB=mysql; MW=1.23.5; VIRTUOSO=6.1
      php: 5.4
    - env: DB=mysql; MW=1.24.1; SESAME=2.7.14
      php: 5.4
    - env: DB=sqlite; MW=1.22.12;
      php: 5.5
    - env: DB=postgres; MW=1.19.20;
      php: 5.4
    - env: DB=sqlite; MW=master@5cc1f1d; PHPUNIT=4.3.*
      php: hhvm-nightly
    - env: DB=mysql; MW=master@5cc1f1d; PHPUNIT=4.3.*; TYPE=benchmark
      php: hhvm
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - env: DB=mysql; MW=1.19.20; TYPE=relbuild
    - env: DB=postgres; MW=1.19.20;
    - php: hhvm-nightly

install:
  - bash ./build/travis/install-services.sh
  - bash ./build/travis/install-mediawiki.sh
  - bash ./build/travis/install-semantic-mediawiki.sh

before_script:
  - bash ./build/travis/update-configuration-settings.sh

script:
  - bash ./build/travis/run-tests.sh

after_success:
  - bash ./build/travis/upload-coverage-report.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#semantic-mediawiki"
    on_success: never
    on_failure: always
